#!/usr/bin/env bash
#####################################################################
# Author    : Erik Dubois
# Website   : https://kiroproject.be
#####################################################################
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
# Purpose:
#   Generate a colour palette from the current wallpaper with pywal and
#   fan it out to the whole Kiro sway desktop: waybar (colors.css), mako
#   (notification colours), and sway window borders (config.d/35-colors).
#   Then live-reload each surface.
# Why:
#   The edition's theming engine — one wallpaper drives every colour. Run
#   at login from sway's autostart, or by hand with a wallpaper path to
#   re-theme: set-theme.sh ~/Pictures/some.jpg
#####################################################################

set -euo pipefail

WALLPAPER="${1:-$HOME/.config/sway/bg/kiro.jpg}"
CACHE="$HOME/.cache/wal/colors.sh"
WAYBAR_COLORS="$HOME/.config/waybar/colors.css"
MAKO_CONFIG="$HOME/.config/mako/config"
SWAY_COLORS="$HOME/.config/sway/config.d/35-colors"

command -v wal >/dev/null 2>&1 || { echo "pywal (wal) not installed — skipping theme"; exit 0; }
[ -f "$WALLPAPER" ] || { echo "Wallpaper not found: $WALLPAPER"; exit 0; }

# Generate the palette. -n: do not set the wallpaper (swaybg owns that). -q: quiet.
wal -i "$WALLPAPER" -n -q

# shellcheck source=/dev/null
source "$CACHE"   # exports $background $foreground $color0 … $color15

# ── waybar — regenerate colors.css, then signal waybar to reload ──────────────
cat > "$WAYBAR_COLORS" <<EOF
/* Generated by set-theme.sh (pywal) from ${WALLPAPER##*/}. */
@define-color bg      ${background};
@define-color fg      ${foreground};
@define-color muted   ${color8};
@define-color accent  ${color4};
@define-color accent2 ${color5};
@define-color info    ${color6};
@define-color good    ${color2};
@define-color warn    ${color3};
@define-color crit    ${color1};
EOF

# ── mako — rewrite the colour lines ───────────────────────────────────────────
if [ -f "$MAKO_CONFIG" ]; then
    sed -i \
        -e "s|^background-color=.*|background-color=${background}|" \
        -e "s|^text-color=.*|text-color=${foreground}|" \
        -e "s|^border-color=.*|border-color=${color4}|" \
        "$MAKO_CONFIG"
fi

# ── sway window colours — regenerate config.d/35-colors ───────────────────────
# Order: border background text indicator child_border
cat > "$SWAY_COLORS" <<EOF
# Generated by set-theme.sh (pywal) from ${WALLPAPER##*/}.
client.focused          ${color4} ${background} ${foreground} ${color4} ${color4}
client.focused_inactive ${color8} ${background} ${foreground} ${color8} ${color8}
client.unfocused        ${color8} ${background} ${color8} ${color8} ${color8}
client.urgent           ${color1} ${background} ${background} ${color1} ${color1}
client.placeholder      ${background} ${background} ${foreground} ${background} ${background}
EOF

# ── Reload the live surfaces ──────────────────────────────────────────────────
pkill -SIGUSR2 waybar 2>/dev/null || true   # waybar reloads its CSS on SIGUSR2
makoctl reload 2>/dev/null || true
swaymsg reload 2>/dev/null || true

echo "Theme applied from ${WALLPAPER##*/}"
