# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1B1A22)
$foreground = rgb(ECF4CE)
$color0 = rgb(424149)
$color1 = rgb(054646)
$color2 = rgb(931D2B)
$color3 = rgb(861592)
$color4 = rgb(18918C)
$color5 = rgb(20972B)
$color6 = rgb(96A956)
$color7 = rgb(DBE7B0)
$color8 = rgb(99A27B)
$color9 = rgb(065D5D)
$color10 = rgb(C42639)
$color11 = rgb(B31CC2)
$color12 = rgb(20C1BA)
$color13 = rgb(2BC93A)
$color14 = rgb(C8E172)
$color15 = rgb(DBE7B0)
