# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000513)
$foreground = rgb(CAEAF2)
$color0 = rgb(171E27)
$color1 = rgb(226384)
$color2 = rgb(2D6F8C)
$color3 = rgb(387B94)
$color4 = rgb(43869C)
$color5 = rgb(4E92A4)
$color6 = rgb(4E92A4)
$color7 = rgb(ABD8E4)
$color8 = rgb(7897A0)
$color9 = rgb(2D85B1)
$color10 = rgb(3C94BB)
$color11 = rgb(4BA4C6)
$color12 = rgb(59B3D0)
$color13 = rgb(68C3DB)
$color14 = rgb(68C3DB)
$color15 = rgb(ABD8E4)
