# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000400)
$foreground = rgb(DFE6E7)
$color0 = rgb(0A1508)
$color1 = rgb(1D471F)
$color2 = rgb(4F5F5B)
$color3 = rgb(4F6159)
$color4 = rgb(56783F)
$color5 = rgb(598036)
$color6 = rgb(7A8B8C)
$color7 = rgb(C9D4D4)
$color8 = rgb(8C9494)
$color9 = rgb(275F29)
$color10 = rgb(697F7A)
$color11 = rgb(6A8177)
$color12 = rgb(73A054)
$color13 = rgb(76AB48)
$color14 = rgb(A3B9BA)
$color15 = rgb(C9D4D4)
