-- Generated by nwg-displays on 2026-07-21 at 14:42:57. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "1920x1195",
    scale = 1.0
})
hl.monitor({
    output = "DVI-I-1",
    mode = "1920x1080@74.97",
    position = "1920x115",
    scale = 1.0
})
hl.monitor({
    output = "DVI-I-2",
    mode = "1920x1080@74.97",
    position = "0x115",
    scale = 1.0
})
