-- Generated by nwg-displays on 2026-08-02 at 22:16:46. Do not edit manually.

hl.monitor({
    output = "desc:BOE 0x0C4E",
    disabled = true
})
hl.monitor({
    output = "desc:HP Inc. HP 24mh 3CM4431D2Z",
    mode = "1920x1080@74.97",
    position = "1920x115",
    scale = 1.0
})
hl.monitor({
    output = "desc:HP Inc. HP 24mh 3CM21209C8",
    mode = "1920x1080@74.97",
    position = "0x115",
    scale = 1.0
})
