-- Generated by nwg-displays on 2026-08-02 at 22:18:55. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "desc:HP Inc. HP 24mh 3CM21209C8",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "desc:HP Inc. HP 24mh 3CM21209C8"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "desc:HP Inc. HP 24mh 3CM21209C8"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "desc:HP Inc. HP 24mh 3CM21209C8"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "desc:HP Inc. HP 24mh 3CM4431D2Z",
    default = true
})
hl.workspace_rule({
    workspace = "6",
    monitor = "desc:HP Inc. HP 24mh 3CM4431D2Z"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "desc:HP Inc. HP 24mh 3CM4431D2Z"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "desc:HP Inc. HP 24mh 3CM4431D2Z"
})
