-- Generated by nwg-displays on 2026-07-21 at 14:42:51. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DVI-I-2",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DVI-I-2"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "DVI-I-2"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "DVI-I-2"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "DVI-I-1",
    default = true
})
hl.workspace_rule({
    workspace = "6",
    monitor = "DVI-I-1"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "DVI-I-1"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "DVI-I-1"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "10",
    monitor = "eDP-1"
})
